## Manually deploy the code
on:
  workflow_dispatch:
  push:
    branches:
      - dev

name: Deploy Chalice backend

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install and deploy Chalice
        run: |
          echo "Moving to Chalice directory"
          cd backend/pms-core
          echo "Install Chalice"
          python -m pip install chalice
          echo "Deploy using Chalice command"
          chalice deploy
